# mypy-pre-commit.ini
[mypy]
python_version = 3.12
namespace_packages = True
explicit_package_bases = True
ignore_missing_imports = True
disable_error_code = import-untyped,import-not-found


[mypy-src.*.migrations.*]
ignore_errors = True
